### ISSUE TITLE
滑块验证报错 NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by dragon0629** [mamoe/mirai#1937]
### 问题描述

![image](https://user-images.githubusercontent.com/29683336/158516042-9f0517a4-c8aa-41e6-b53f-b59d163b4f56.png)
2.9 正常可用，用2.9可正常出请求数字码，并完成过程
2.10 新号登录出这个提示报错
日志么有什么明显问题

另外请问一下是否有更直接一点的官方登录模式哇，现在群里问问登录真是五花八门，有抓包的，有改浏览器协议头的，有用miraiandroid的，有用texcapter滑块助手的。

### 复现

100%复现，全新号登录必出，2.10
输入login qq password后即可见到。

换回2.9一切正常

### mirai-core 版本

2.10.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

无

### 系统日志

```text
2022-03-16 12:15:13 V/main: Loading configurations...
2022-03-16 12:15:13 V/main: Loading JVM plugins...
2022-03-16 12:15:13 V/main: 0 external PluginLoader(s) found.
2022-03-16 12:15:13 V/main: Loading PermissionService...
2022-03-16 12:15:13 V/main: Reloaded PermissionService settings.
2022-03-16 12:15:13 V/main: Loading built-in commands...
2022-03-16 12:15:13 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-03-16 12:15:13 V/main: Enabling plugins...
2022-03-16 12:15:14 I/main: mirai-console started successfully.
> login 2354328553 pass*****
2022-03-16 12:15:33 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2022-03-16 12:15:33 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2022-03-16 12:15:33 V/main: Bot 2354328553 working in D:\MIRAI_2.10.0\bots\2354328553
2022-03-16 12:15:33 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-03-16 12:15:33 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-03-16 12:15:33 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-03-16 12:15:33 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
libpng warning: iCCP: cHRM chunk does not match sRGB
```

**Comment by Karlatemp** [comment]
Use java 11+, 这是 ktor 的问题

**Comment by mckuhei** [comment]
> Use java 11+, 这是 ktor 的问题

这个是Java 9以上的编译器的问题，和kt没问题

**Comment by kukume** [comment]
https://www.kuku.me/archives/25/
试试我的自动过滑块？
当然，你也可以手动输入验证码url进行识别  https://api.kukuqaq.com/tool/captcha

**Comment by dragon0629** [comment]
2.11 貌似修复了，关闭了，感谢辛苦工作！
